
services:
  frontend:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network
    

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
